# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/JKSteppedProgressBar.xcworkspace -scheme JKSteppedProgressBar-Example -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
